import Head from "next/head";
import Button from "components/Button";
import styled from "styled-components";
import Timer from "components/Timer";
import { Arrow } from "components/ArrowDivider";
export default function Home() {
  const HeroSection = styled.section`
    background-image: url("/assets/backgrounds/HeroSectionImage.png");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 100%;
  `;
  const Glass = styled.div`
    background-color: ${(props) =>
      props.background || "rgba(255, 255, 255, 1)"};
    padding: 1rem 1.5rem;
    border-radius: 12px;
    color: #fff;
  `;
  const VerticalLine = styled.div`
    border-left: 1px solid #fff;
  `;

  return (
    <>
      <Head>
        <title>Programa de Pós Graduação em Gestão de Saúde - INAED</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection className="px-4 py-4 md:px-20 md:py-6 ">
          <header>
            <div className="flex lg:justify-between items-center">
              <div>
                <img
                  src="/assets/logos/logo.svg"
                  alt="Logo"
                  className="hidden lg:block"
                />
              </div>
              <div>
                <img
                  src="/assets/logos/logo.svg"
                  alt="Logo Pós"
                  className="w-2/3"
                />
              </div>
              <div className="hidden md:contents">
                <Button text="Quero me inscrever agora!" />
              </div>
            </div>
          </header>
          <div className=" mt-8 grid grid-cols-4 md:grid-cols-8 lg:grid-cols-12 gap-4 md:gap-6">
            <div className="flex flex-col justify-center col-span-4 md:col-span-8 lg:col-span-5">
              <h1 className="text-3xl lg:text-4xl font-bold text-primaryGreen">
                Veja no que você precisa investir para ser um profissional de
                sucesso em um negócio de saúde
              </h1>
              <h3 className="text-2xl py-6 text-lightColor">
                (Spoiler: a resposta já está neste título)
              </h3>
              <Button text="Faça a sua inscrição agora mesmo!" />
              <Glass
                background="rgba(255, 255, 255, 0.25)"
                className="my-4 flex font-bold justify-center"
              >
                <div className="flex items-center">
                  <img
                    src="/assets/svg/calendar.svg"
                    alt="icone-calendario"
                    className="mr-2"
                  />
                  <span>Inscrições até março</span>
                </div>
                <VerticalLine className="mx-2" />
                <div className="flex items-center">
                  <img
                    src="/assets/svg/student.svg"
                    alt="icone-aluno"
                    className="mr-2"
                  />
                  <span>Início previsto: 14/04/2023</span>
                </div>
              </Glass>
              <div className="col-span-6">
                <Glass
                  background="rgba(33, 39, 56, 0.25)"
                  className="flex flex-col justify-center items-center"
                >
                  <Timer endDate="2023-04-14T23:59:59" />
                  <span className="hidden md:block md:mt-2 font-bold text-base">
                    Para você garantir a sua vaga. Não perca!
                  </span>
                </Glass>
              </div>
            </div>

            <div className="hidden lg:block col-start-8 col-span-7">
              <img src="/assets/images/doctor.png" alt="Imagem Doutor" />
            </div>
          </div>
        </HeroSection>
        <Arrow />
      </main>
    </>
  );
}
